"""
Signal Rejection Tracker — Execution Path Audit.

Every signal that reaches the execution bridge gets a structured trace
that records the outcome of each gate:
  1. Scanner → candidate created
  2. Session filter → pass/fail + reason
  3. Cycle limit → pass/fail
  4. Cooldown → pass/fail
  5. Duplicate position → pass/fail
  6. Risk check → pass/fail + reason
  7. Ghost filter (qty=0) → pass/fail
  8. Position opened → yes/no

Each trace is written to `data/logs/signal_trace.jsonl` and kept
in memory for the dashboard Pipeline Monitor.
"""
from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Dict, List, Optional
from loguru import logger


TRACE_LOG_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data", "logs")
TRACE_LOG_FILE = os.path.join(TRACE_LOG_DIR, "signal_trace.jsonl")


@dataclass
class GateResult:
    """Result of a single gate evaluation."""
    gate_name: str
    passed: bool
    reason: str = ""
    details: Dict = field(default_factory=dict)


@dataclass
class SignalTrace:
    """Complete trace of a signal through the execution pipeline."""
    symbol: str
    side: str
    confidence: float
    regime: str = ""
    timestamp: float = 0.0
    signal_id: str = ""
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    risk_reward: float = 0.0
    gates: List[Dict] = field(default_factory=list)
    final_outcome: str = "pending"  # "position_opened" | "rejected" | "pending"
    rejection_gate: str = ""  # which gate rejected it
    rejection_reason: str = ""
    duration_ms: float = 0.0

    def add_gate(self, gate_name: str, passed: bool, reason: str = "", **details):
        """Record the result of a gate evaluation."""
        self.gates.append({
            "gate": gate_name,
            "passed": passed,
            "reason": reason,
            "details": details,
            "timestamp": time.time(),
        })
        if not passed and self.final_outcome == "pending":
            self.final_outcome = "rejected"
            self.rejection_gate = gate_name
            self.rejection_reason = reason

    def mark_opened(self, position_id: str = ""):
        """Mark signal as successfully opened as a position."""
        self.final_outcome = "position_opened"
        self.rejection_gate = ""
        self.rejection_reason = ""
        self.gates.append({
            "gate": "position_opened",
            "passed": True,
            "reason": f"Position ID: {position_id}",
            "timestamp": time.time(),
        })

    def to_dict(self) -> Dict:
        """Convert to dictionary for JSON serialization."""
        d = asdict(self)
        d["duration_ms"] = round(self.duration_ms, 2)
        return d

    def format_report(self) -> str:
        """Format as human-readable report block."""
        lines = [
            f"{'='*55}",
            f"Symbol: {self.symbol}",
            f"Signal ID: {self.signal_id}",
            f"Side: {self.side}  |  Confidence: {self.confidence:.1f}%",
            f"Entry: {self.entry_price:.6f}  |  SL: {self.stop_loss:.6f}  |  TP: {self.take_profit:.6f}",
            f"R:R: {self.risk_reward:.2f}  |  Regime: {self.regime}",
            f"{'─'*55}",
        ]
        for g in self.gates:
            status = "✅ PASS" if g["passed"] else "❌ FAIL"
            reason = f" — {g['reason']}" if g.get("reason") else ""
            lines.append(f"  {g['gate']:<25} {status}{reason}")
        lines.append(f"{'─'*55}")
        if self.final_outcome == "position_opened":
            lines.append(f"  FINAL: 🚀 POSITION OPENED")
        else:
            lines.append(f"  FINAL: ❌ REJECTED by {self.rejection_gate}")
            lines.append(f"  Reason: {self.rejection_reason}")
        lines.append(f"  Duration: {self.duration_ms:.1f}ms")
        lines.append(f"{'='*55}")
        return "\n".join(lines)


class SignalRejectionTracker:
    """
    Tracks every signal through the execution pipeline.
    
    Usage:
        tracker = SignalRejectionTracker()
        trace = tracker.start_trace(symbol, side, confidence, ...)
        trace.add_gate("session_filter", passed=True)
        trace.add_gate("risk_check", passed=False, reason="max positions reached")
        tracker.finish_trace(trace)
    """

    def __init__(self):
        self._traces: List[SignalTrace] = []
        self._rejected: List[SignalTrace] = []
        self._opened: List[SignalTrace] = []
        self._daily_counts: Dict[str, int] = {
            "generated": 0,      # Signals generated by scanner
            "published": 0,      # Signals that passed session filter
            "total": 0,          # Signals entering execution bridge
            "passed": 0,         # Positions opened
            "rejected": 0,       # Rejected by any gate
            "rejected_session": 0,
            "rejected_risk": 0,
            "rejected_cooldown": 0,
            "rejected_cycle_limit": 0,
            "rejected_duplicate": 0,
            "rejected_ghost": 0,
            "rejected_other": 0,
        }
        self._reconciliation_log: List[Dict] = []
        # Ensure log directory exists
        os.makedirs(TRACE_LOG_DIR, exist_ok=True)

    def record_generated(self):
        """Record that a signal was generated by the scanner."""
        self._daily_counts["generated"] += 1

    def record_published(self):
        """Record that a signal passed session filter and was published."""
        self._daily_counts["published"] += 1

    def start_trace(
        self,
        symbol: str,
        side: str,
        confidence: float,
        regime: str = "",
        signal_id: str = "",
        entry_price: float = 0.0,
        stop_loss: float = 0.0,
        take_profit: float = 0.0,
        risk_reward: float = 0.0,
    ) -> SignalTrace:
        """Begin tracking a new signal."""
        trace = SignalTrace(
            symbol=symbol,
            side=side,
            confidence=confidence,
            regime=regime,
            timestamp=time.time(),
            signal_id=signal_id,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward=risk_reward,
        )
        self._daily_counts["total"] += 1
        return trace

    def finish_trace(self, trace: SignalTrace):
        """Record the completed trace and write to log file."""
        trace.duration_ms = (time.time() - trace.timestamp) * 1000
        
        self._traces.append(trace)
        
        if trace.final_outcome == "position_opened":
            self._opened.append(trace)
            self._daily_counts["passed"] += 1
        else:
            self._rejected.append(trace)
            # Categorize rejection by gate
            gate = trace.rejection_gate.lower()
            if "session" in gate:
                self._daily_counts["rejected_session"] += 1
            elif "risk" in gate:
                self._daily_counts["rejected_risk"] += 1
                self._daily_counts["rejected"] += 1  # Execution gate rejection
            elif "cooldown" in gate:
                self._daily_counts["rejected_cooldown"] += 1
                self._daily_counts["rejected"] += 1  # Execution gate rejection
            elif "cycle" in gate:
                self._daily_counts["rejected_cycle_limit"] += 1
                self._daily_counts["rejected"] += 1  # Execution gate rejection
            elif "duplicate" in gate:
                self._daily_counts["rejected_duplicate"] += 1
                self._daily_counts["rejected"] += 1  # Execution gate rejection
            elif "ghost" in gate:
                self._daily_counts["rejected_ghost"] += 1
                self._daily_counts["rejected"] += 1  # Execution gate rejection
            else:
                self._daily_counts["rejected_other"] += 1
                self._daily_counts["rejected"] += 1  # Execution gate rejection

        # Write to JSONL log file
        self._write_trace(trace)
        
        # Log the formatted report
        report = trace.format_report()
        if trace.final_outcome == "position_opened":
            logger.info("\n" + report)
        else:
            logger.warning("\n" + report)

    def _write_trace(self, trace: SignalTrace):
        """Append trace to JSONL log file."""
        try:
            with open(TRACE_LOG_FILE, "a") as f:
                f.write(json.dumps(trace.to_dict()) + "\n")
        except Exception as e:
            logger.error("Failed to write signal trace: {}", e)

    def get_daily_summary(self) -> Dict:
        """Get daily rejection statistics."""
        return dict(self._daily_counts)

    def run_reconciliation(self) -> Dict:
        """Run daily reconciliation check.
        
        Identity: Generated = Published + Rejected_by_session_filter
                  Published = Opened + Rejected_by_execution_gates
        
        Returns reconciliation result with any discrepancies.
        """
        s = self._daily_counts
        
        # Level 1: Scanner → Session Filter
        session_rejected = s.get("rejected_session", 0)
        level1_ok = (s["generated"] == s["published"] + session_rejected)
        level1_diff = s["generated"] - (s["published"] + session_rejected)
        
        # Level 2: Session Filter → Execution
        level2_ok = (s["published"] == s["passed"] + s["rejected"])
        level2_diff = s["published"] - (s["passed"] + s["rejected"])
        
        # Overall: Generated = Opened + All Rejections
        total_rejected = (s["rejected_session"] + s["rejected_risk"] + 
                         s["rejected_cooldown"] + s["rejected_cycle_limit"] +
                         s["rejected_duplicate"] + s["rejected_ghost"] +
                         s["rejected_other"])
        overall_ok = (s["generated"] == s["passed"] + total_rejected)
        
        result = {
            "timestamp": time.time(),
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "level1": {
                "name": "Scanner → Session Filter",
                "generated": s["generated"],
                "session_rejected": session_rejected,
                "published": s["published"],
                "identity_ok": level1_ok,
                "discrepancy": level1_diff,
            },
            "level2": {
                "name": "Session Filter → Execution",
                "published": s["published"],
                "opened": s["passed"],
                "execution_rejected": s["rejected"],
                "identity_ok": level2_ok,
                "discrepancy": level2_diff,
            },
            "overall": {
                "generated": s["generated"],
                "opened": s["passed"],
                "total_rejected": total_rejected,
                "identity_ok": overall_ok,
                "discrepancy": s["generated"] - (s["passed"] + total_rejected),
            },
        }
        
        self._reconciliation_log.append(result)
        
        # Log discrepancies as warnings
        if not level1_ok:
            logger.warning("⚠️ RECONCILIATION L1 FAIL: Generated={} but Published+SessionRejected={} (diff={})",
                          s["generated"], s["published"] + session_rejected, level1_diff)
        if not level2_ok:
            logger.warning("⚠️ RECONCILIATION L2 FAIL: Published={} but Opened+ExecRejected={} (diff={})",
                          s["published"], s["passed"] + s["rejected"], level2_diff)
        if overall_ok:
            logger.info("✅ RECONCILIATION OK: Generated={} = Opened({}) + Rejected({})",
                       s["generated"], s["passed"], total_rejected)
        
        return result

    def format_reconciliation_report(self, result: Dict = None) -> str:
        """Format reconciliation report as readable text."""
        if result is None:
            result = self.run_reconciliation()
        
        s = self._daily_counts
        total_rejected = (s["rejected_session"] + s["rejected_risk"] + 
                         s["rejected_cooldown"] + s["rejected_cycle_limit"] +
                         s["rejected_duplicate"] + s["rejected_ghost"] +
                         s["rejected_other"])
        
        l1 = result["level1"]
        l2 = result["level2"]
        overall = result["overall"]
        
        l1_status = "✅" if l1["identity_ok"] else "❌ DISCREPANCY"
        l2_status = "✅" if l2["identity_ok"] else "❌ DISCREPANCY"
        overall_status = "✅" if overall["identity_ok"] else "❌ DISCREPANCY"
        
        lines = [
            f"╔═══════════════════════════════════════════════════╗",
            f"║  DAILY RECONCILIATION REPORT — {result['date']}       ║",
            f"╠═══════════════════════════════════════════════════╣",
            f"║                                                   ║",
            f"║  GENERATED............ {s['generated']:>6}                     ║",
            f"║                                                   ║",
            f"║  Level 1: Scanner → Session Filter {l1_status:<14}║",
            f"║    Published.......... {s['published']:>6}                     ║",
            f"║    Session Rejected... {s['rejected_session']:>6}                     ║",
            f"║    Identity: {s['published']} + {s['rejected_session']} = {s['published'] + s['rejected_session']} {l1_status}     ║",
            f"║                                                   ║",
            f"║  Level 2: Session → Execution {l2_status:<17}║",
            f"║    Opened............. {s['passed']:>6}                     ║",
            f"║    Execution Rejected. {s['rejected']:>6}                     ║",
            f"║    Identity: {s['passed']} + {s['rejected']} = {s['passed'] + s['rejected']} {l2_status}         ║",
            f"║                                                   ║",
            f"║  REJECTION BREAKDOWN:                             ║",
            f"║    Session filter:     {s['rejected_session']:>6}                     ║",
            f"║    Risk check:         {s['rejected_risk']:>6}                     ║",
            f"║    Cooldown:           {s['rejected_cooldown']:>6}                     ║",
            f"║    Cycle limit:        {s['rejected_cycle_limit']:>6}                     ║",
            f"║    Duplicate position: {s['rejected_duplicate']:>6}                     ║",
            f"║    Ghost (qty=0):      {s['rejected_ghost']:>6}                     ║",
            f"║    Other:              {s['rejected_other']:>6}                     ║",
            f"║                                                   ║",
            f"║  OVERALL: {overall_status:<37}║",
            f"║    Generated({s['generated']}) = Opened({s['passed']}) + Rejected({total_rejected})    ║",
            f"╚═══════════════════════════════════════════════════╝",
        ]
        return "\n".join(lines)

    def get_recent_rejections(self, limit: int = 20) -> List[SignalTrace]:
        """Get most recent rejected signals."""
        return self._rejected[-limit:]

    def get_recent_traces(self, limit: int = 50) -> List[SignalTrace]:
        """Get most recent traces (all outcomes)."""
        return self._traces[-limit:]

    def get_rejection_breakdown(self) -> Dict[str, int]:
        """Get rejection counts by gate."""
        breakdown: Dict[str, int] = {}
        for t in self._rejected:
            gate = t.rejection_gate
            breakdown[gate] = breakdown.get(gate, 0) + 1
        return breakdown

    def format_daily_summary(self) -> str:
        """Format daily summary as readable text."""
        s = self._daily_counts
        total = s["total"] or 1
        pass_rate = (s["passed"] / total) * 100
        
        lines = [
            f"╔═══════════════════════════════════════════════════╗",
            f"║  SIGNAL REJECTION TRACKER — DAILY SUMMARY         ║",
            f"╠═══════════════════════════════════════════════════╣",
            f"║  Generated (scanner):    {s['generated']:>6}                 ║",
            f"║  Published (post-session):{s['published']:>5}                 ║",
            f"║  Total evaluated:        {s['total']:>6}                 ║",
            f"║  Positions opened:       {s['passed']:>6}  ({pass_rate:.1f}%)        ║",
            f"║  Rejected:               {s['rejected']:>6}  ({100-pass_rate:.1f}%)        ║",
            f"╠═══════════════════════════════════════════════════╣",
            f"║  REJECTION BREAKDOWN:                             ║",
            f"║    Session filter:       {s['rejected_session']:>6}                 ║",
            f"║    Risk check:           {s['rejected_risk']:>6}                 ║",
            f"║    Cooldown:             {s['rejected_cooldown']:>6}                 ║",
            f"║    Cycle limit:          {s['rejected_cycle_limit']:>6}                 ║",
            f"║    Duplicate position:   {s['rejected_duplicate']:>6}                 ║",
            f"║    Ghost (qty=0):        {s['rejected_ghost']:>6}                 ║",
            f"║    Other:                {s['rejected_other']:>6}                 ║",
            f"╚═══════════════════════════════════════════════════╝",
        ]
        return "\n".join(lines)


# ── Singleton instance ──
_tracker_instance: Optional[SignalRejectionTracker] = None


def get_tracker() -> SignalRejectionTracker:
    """Get or create the singleton tracker instance."""
    global _tracker_instance
    if _tracker_instance is None:
        _tracker_instance = SignalRejectionTracker()
    return _tracker_instance
