"""
Trade Attribution Logger — Complete decision trail for every trade.

For each trade, records:
    Trade ID
    Generated By: EMA V5
    Validated By: Smart Money
    Accepted By: App
    Reasons:
        • Institution Agreement
        • Expectancy
        • Reward/Risk
        • Correlation
        • Portfolio Heat
    Exit: Trailing Stop
    Result: +2.4R
    Largest Favourable Excursion: 3.1R
    Largest Adverse Excursion: 0.7R

This becomes invaluable when diagnosing why trades succeeded or failed.

READ-ONLY: never modifies upstream data.
"""
from __future__ import annotations

import json
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from loguru import logger


_DB_PATH = Path(__file__).resolve().parent.parent / "data" / "institutional_v1.db"


@dataclass
class TradeAttribution:
    """Complete attribution for a single trade."""
    trade_id: str = ""
    symbol: str = ""
    side: str = ""

    # Source
    generated_by: str = "EMA V5 Scanner"
    validated_by: str = "Smart Money"
    accepted_by: str = "App Decision Layer"

    # Acceptance reasons
    reasons: List[str] = field(default_factory=list)

    # Quality scores at entry
    trade_quality_score: float = 0.0
    institution_agreement: float = 0.0
    expected_value_r: float = 0.0
    regime: str = ""
    risk_reward: float = 0.0
    portfolio_heat_pct: float = 0.0
    correlation_reduction: float = 1.0
    execution_quality: float = 0.0

    # Execution
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    quantity: float = 0.0
    leverage: int = 10

    # Outcome
    exit_price: float = 0.0
    exit_reason: str = ""
    pnl: float = 0.0
    realized_r: float = 0.0
    hold_minutes: float = 0.0

    # Excursion
    mfe_r: float = 0.0  # Largest Favourable Excursion
    mae_r: float = 0.0  # Largest Adverse Excursion

    # Classification
    priority: str = ""
    decision: str = ""

    # Timestamps
    entry_time: float = 0.0
    exit_time: float = 0.0

    def to_dict(self) -> Dict:
        return {
            "trade_id": self.trade_id,
            "symbol": self.symbol,
            "side": self.side,
            "source": {
                "generated_by": self.generated_by,
                "validated_by": self.validated_by,
                "accepted_by": self.accepted_by,
            },
            "reasons": self.reasons,
            "quality_scores": {
                "trade_quality": round(self.trade_quality_score, 1),
                "institution_agreement": round(self.institution_agreement, 3),
                "expected_value_r": round(self.expected_value_r, 3),
                "regime": self.regime,
                "risk_reward": round(self.risk_reward, 2),
                "portfolio_heat_pct": round(self.portfolio_heat_pct, 2),
                "correlation_reduction": round(self.correlation_reduction, 2),
                "execution_quality": round(self.execution_quality, 1),
            },
            "execution": {
                "entry_price": self.entry_price,
                "stop_loss": self.stop_loss,
                "take_profit": self.take_profit,
                "quantity": round(self.quantity, 6),
                "leverage": self.leverage,
            },
            "outcome": {
                "exit_price": self.exit_price,
                "exit_reason": self.exit_reason,
                "pnl": round(self.pnl, 4),
                "realized_r": round(self.realized_r, 3),
                "hold_minutes": round(self.hold_minutes, 0),
                "mfe_r": round(self.mfe_r, 3),
                "mae_r": round(self.mae_r, 3),
            },
            "classification": {
                "priority": self.priority,
                "decision": self.decision,
            },
            "timestamps": {
                "entry": self.entry_time,
                "exit": self.exit_time,
            },
        }

    def render(self) -> str:
        """Render trade attribution as human-readable summary."""
        lines = []
        lines.append(f"═══ TRADE ATTRIBUTION: {self.symbol} {self.side} ═══")
        lines.append("")
        lines.append(f"Generated By:  {self.generated_by}")
        lines.append(f"Validated By:  {self.validated_by}")
        lines.append(f"Accepted By:   {self.accepted_by}")
        lines.append("")
        lines.append("Reasons:")
        for reason in self.reasons:
            lines.append(f"  • {reason}")
        lines.append("")
        lines.append("Quality Scores:")
        lines.append(f"  • Trade Quality:       {self.trade_quality_score:.1f}/100")
        lines.append(f"  • Institution Agreement: {self.institution_agreement:.0%}")
        lines.append(f"  • Expected Value:      {self.expected_value_r:+.3f}R")
        lines.append(f"  • Risk/Reward:         {self.risk_reward:.2f}")
        lines.append(f"  • Regime:              {self.regime}")
        lines.append(f"  • Portfolio Heat:      {self.portfolio_heat_pct:.1f}%")
        lines.append("")
        lines.append("Execution:")
        lines.append(f"  • Entry:    {self.entry_price}")
        lines.append(f"  • Stop:     {self.stop_loss}")
        lines.append(f"  • Target:   {self.take_profit}")
        lines.append(f"  • Exit:     {self.exit_price}")
        lines.append(f"  • Exit Reason: {self.exit_reason}")
        lines.append("")
        lines.append("Outcome:")
        lines.append(f"  • Result:   {self.realized_r:+.3f}R (${self.pnl:+.2f})")
        lines.append(f"  • Hold:     {self.hold_minutes:.0f} minutes")
        lines.append(f"  • MFE:      {self.mfe_r:+.3f}R (largest favourable)")
        lines.append(f"  • MAE:      {self.mae_r:+.3f}R (largest adverse)")
        lines.append("")
        lines.append(f"Decision: {self.decision} [{self.priority}]")

        return "\n".join(lines)


class TradeAttributionLogger:
    """
    Logs complete attribution for every trade.

    READ-ONLY: never modifies upstream data.
    """

    def __init__(self, db_path: Optional[Path] = None):
        self._db_path = db_path or _DB_PATH
        self._ensure_table()

    def log_trade(self, attribution: TradeAttribution) -> None:
        """Log a complete trade attribution."""
        try:
            conn = sqlite3.connect(str(self._db_path), timeout=10)
            cur = conn.cursor()

            cur.execute("""
                INSERT INTO trade_attribution (
                    trade_id, symbol, side,
                    generated_by, validated_by, accepted_by,
                    reasons,
                    trade_quality_score, institution_agreement, expected_value_r,
                    regime, risk_reward, portfolio_heat_pct, correlation_reduction,
                    execution_quality,
                    entry_price, stop_loss, take_profit, quantity, leverage,
                    exit_price, exit_reason, pnl, realized_r, hold_minutes,
                    mfe_r, mae_r,
                    priority, decision,
                    entry_time, exit_time,
                    timestamp
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                attribution.trade_id, attribution.symbol, attribution.side,
                attribution.generated_by, attribution.validated_by, attribution.accepted_by,
                json.dumps(attribution.reasons),
                attribution.trade_quality_score, attribution.institution_agreement,
                attribution.expected_value_r,
                attribution.regime, attribution.risk_reward, attribution.portfolio_heat_pct,
                attribution.correlation_reduction, attribution.execution_quality,
                attribution.entry_price, attribution.stop_loss, attribution.take_profit,
                attribution.quantity, attribution.leverage,
                attribution.exit_price, attribution.exit_reason, attribution.pnl,
                attribution.realized_r, attribution.hold_minutes,
                attribution.mfe_r, attribution.mae_r,
                attribution.priority, attribution.decision,
                attribution.entry_time, attribution.exit_time,
                time.time(),
            ))

            conn.commit()
            conn.close()

            logger.debug(
                "ATTRIBUTION: {} {} {}R — {} ({})",
                attribution.symbol, "WIN" if attribution.pnl > 0 else "LOSS",
                attribution.realized_r, attribution.exit_reason, attribution.priority,
            )

        except Exception as e:
            logger.warning("Trade attribution error: {}", e)

    def get_attributions(
        self,
        symbol: Optional[str] = None,
        limit: int = 100,
    ) -> List[Dict]:
        """Get trade attributions."""
        try:
            conn = sqlite3.connect(str(self._db_path), timeout=10)
            conn.row_factory = sqlite3.Row
            cur = conn.cursor()

            query = "SELECT * FROM trade_attribution"
            params = []

            if symbol:
                query += " WHERE symbol = ?"
                params.append(symbol)

            query += " ORDER BY timestamp DESC LIMIT ?"
            params.append(limit)

            cur.execute(query, params)
            rows = [dict(r) for r in cur.fetchall()]
            conn.close()

            return rows

        except Exception as e:
            logger.warning("Attribution query error: {}", e)
            return []

    def get_summary(self) -> Dict:
        """Get attribution summary statistics."""
        try:
            conn = sqlite3.connect(str(self._db_path), timeout=10)
            cur = conn.cursor()

            cur.execute("""
                SELECT
                    COUNT(*) as total,
                    SUM(CASE WHEN pnl > 0 THEN 1 ELSE 0 END) as wins,
                    AVG(realized_r) as avg_r,
                    AVG(trade_quality_score) as avg_tq,
                    AVG(institution_agreement) as avg_inst,
                    AVG(expected_value_r) as avg_ev
                FROM trade_attribution
            """)
            row = cur.fetchone()

            # Exit reason breakdown
            cur.execute("""
                SELECT exit_reason, COUNT(*), AVG(pnl)
                FROM trade_attribution
                GROUP BY exit_reason
                ORDER BY COUNT(*) DESC
            """)
            exits = cur.fetchall()

            conn.close()

            return {
                "total_trades": row[0] if row else 0,
                "win_rate": (row[1] / row[0] * 100) if row and row[0] and row[1] else 0,
                "avg_realized_r": row[2] if row else 0,
                "avg_trade_quality": row[3] if row else 0,
                "avg_institution_agreement": row[4] if row else 0,
                "avg_expected_value": row[5] if row else 0,
                "exit_breakdown": [
                    {"reason": e[0], "count": e[1], "avg_pnl": round(e[2], 4)}
                    for e in exits
                ],
            }

        except Exception as e:
            logger.warning("Attribution summary error: {}", e)
            return {}

    def _ensure_table(self) -> None:
        """Create attribution table if it doesn't exist."""
        try:
            conn = sqlite3.connect(str(self._db_path), timeout=10)
            cur = conn.cursor()

            cur.execute("""
                CREATE TABLE IF NOT EXISTS trade_attribution (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    trade_id TEXT,
                    symbol TEXT,
                    side TEXT,
                    generated_by TEXT,
                    validated_by TEXT,
                    accepted_by TEXT,
                    reasons TEXT,
                    trade_quality_score REAL,
                    institution_agreement REAL,
                    expected_value_r REAL,
                    regime TEXT,
                    risk_reward REAL,
                    portfolio_heat_pct REAL,
                    correlation_reduction REAL,
                    execution_quality REAL,
                    entry_price REAL,
                    stop_loss REAL,
                    take_profit REAL,
                    quantity REAL,
                    leverage INTEGER,
                    exit_price REAL,
                    exit_reason TEXT,
                    pnl REAL,
                    realized_r REAL,
                    hold_minutes REAL,
                    mfe_r REAL,
                    mae_r REAL,
                    priority TEXT,
                    decision TEXT,
                    entry_time REAL,
                    exit_time REAL,
                    timestamp REAL
                )
            """)

            cur.execute("CREATE INDEX IF NOT EXISTS idx_attr_symbol ON trade_attribution(symbol)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_attr_decision ON trade_attribution(decision)")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_attr_timestamp ON trade_attribution(timestamp)")

            conn.commit()
            conn.close()

        except Exception as e:
            logger.warning("Attribution table creation error: {}", e)
